CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'oozcan'@'%' IDENTIFIED BY 'pass123';
GRANT ALL PRIVILAGES ON wordpress.* TO 'oozcan'@'%';
FLUSH PRIVILAGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
